//v105 (c) 2008-2014 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
if(typeof Tynt.TCL=="undefined"){(function(){var ia=function(i,h){function L(a){var b=L.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},e=14;e--;)c[b.key[e]]=a[e]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(f,g,d){if(g)c[b.q.name][g]=d});return c}L.options={strictMode:false,key:["source","protocol","authority","userInfo","user","password","host","port","relative","path","directory","file","query","anchor"],q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,
loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};var r=h.body,p=h.documentElement,Y=i.eval("/*@cc_on!@*/false"),M=function(a,b){for(var c="",e=0;e<b;e++)c+=a;return c},u=M("a",50),v=(Tynt.e||"")+"ic.tynt.com",Z=(Tynt.e||"")+"de.tynt.com/deb/",N=v+"/b/s",z=function(a){return a.replace(/^\s+|\s+$/g,"")},E=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=
a[c]},F=function(a){for(var b={},c=a.length,e=[],f=0;f<c;f++)if(!b[a[f]]){b[a[f]]=true;e.push(a[f])}return e},O;O=i.addEventListener?function(a,b,c){a.addEventListener(b,c,false)}:function(a,b,c){a.attachEvent("on"+b,c)};var $=function(a,b){var c=i.location.hostname.split("."),e,f=2;do{e=c.slice(c.length-f,c.length).join(".");e=a+";path=/;domain=."+e+";"+b;h.cookie=e;f++}while(h.cookie.indexOf(a)==-1&&f<=c.length);if(h.cookie.indexOf(a)==-1){e=a+";path=/;"+b;h.cookie=e}},P=function(a){h.readyState==
"complete"?a():O(i,"load",function(){setTimeout(function(){if(typeof h.readyState=="undefined"&&!Y)h.readyState="complete";a()},10)})},n=function(a,b){var c=[],e=function(f,g){var d="http://"+f.replace("id="+u,"id="+F(Tynt).join("~"));if(d.indexOf(v+"/b/p?")>-1&&typeof Tynt.b=="string")d+="&b="+Tynt.b;var j=new Image(1,1);if(g)j.onerror=g;j.src=d};n=function(f,g){c.push([f,g])};P(function(){n=e;for(var f=0;f<c.length;f++)n(c[f][0],c[f][1]);c=null});n(a,b)},Q=function(a){var b=[],c="",e;for(e in a)if(a.hasOwnProperty(e)){b.push(c,
e,"=",a[e]);c="&"}return b.join("")},S=function(a){for(var b=0,c=a.length<100?a.length:100,e=0;e<c;e++)b+=a.charCodeAt(e);a=Math.floor(Math.random()*3844);c=Math.abs((new Date).getTime()-12281184E5);return R(c,7)+R((b+a)%3844,2)},T=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?T(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},R=function(a,b){var c=T(a);return M("0",b-c.length)+c},U=z((h.title||i.location.hostname).toString()).replace(RegExp(i.location.hash,"g"),""),aa=function(){for(var a=h.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")&&a[b].getAttribute("href")){a=a[b].getAttribute("href");b=i.location.protocol+"//"+i.location.host+i.location.pathname;var c=h.getElementsByTagName("base")[0];
if(c)if(c=c.getAttribute("href"))b=c;if(!a.match(/^http/)){if(a.charAt(0)=="/"){c=b.indexOf("/",9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},w=function(a){return a.replace(/^https?:\/\//,"")},ba=function(a,b){for(var c=b+"=",e=a.split(";"),f=0;f<e.length;f++){for(var g=e[f];g.charAt(0)==" ";)g=g.substring(1,g.length);if(g.indexOf(c)===0)return g.substring(c.length,g.length)}return null},ca=function(){var a=ba(h.cookie,"tracertraffic"),
b=encodeURIComponent(w(aa())),c=i.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:false;var e=v+"/b/p?id="+u+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+(new Date).getTime(),f=e+(b?"&cu="+b:""),g=f+(h.referrer?"&r="+encodeURIComponent(w(h.referrer)):"");a=g+"&t="+encodeURIComponent(U);n(a,function(){n(g,function(){n(f,function(){n(e)})})})},da=function(){P(function(){var a={async:"async",src:"http://"+[Z,"v2?id=",F(Tynt).join("~"),"&r=",encodeURIComponent(w(h.referrer))].join("")},b=h.createElement("script");
E(a,b);E(void 0,b.style);a=h.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)})},q=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;a.unshift(b);a.length>3&&a.pop();return true}},ea=q(),fa=q(),ga=function(){var a,b=function(){i.removeEventListener("blur",b,false);G(a);return true};return function(c){a=c.target||c.srcElement;i.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){i.addEventListener("blur",b,
false);setTimeout(function(){h.removeEventListener("blur",b,false)},1E4)}return true}}(),V=function(a){G(a.target||a.srcElement,true)},A,W=function(a){a=a.target||a.srcElement;A=a.nodeName=="IMG"?a:null},H=function(){var a=function(d){return typeof d.pageX=="number"?{x:d.pageX-(p.scrollLeft?p.scrollLeft:r.scrollLeft),y:d.pageY-(p.scrollTop?p.scrollTop:r.scrollTop)}:{x:d.clientX,y:d.clientY}},b=function(d){d=a(d);return d.x<=0||d.y<=0||d.x>=r.clientWidth||d.y>=r.clientHeight},c=function(d){d=a(d);
return d.x<=0||d.y<=0||d.x>=p.clientWidth||d.y>=p.clientHeight},e=function(d){return d.target.nodeName=="#document"},f=function(d){d=a(d);return d.x<=4||d.y<=4||d.x>=p.clientWidth-4||d.y>=p.clientHeight-4},g=function(d){g=navigator.userAgent.match("MSIE")?!h.compatMode||h.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?e:f;g(d)};return function(d){if(A&&g(d)){G(A);A=null}return true}}();Tynt.ci=function(){var a;return function(b,c){a=c||a;var e=N+["?ci=",b,"&id=",u,"&g=",a,
"&r=",encodeURIComponent(w(h.referrer)),"&ts=",(new Date).getTime()].join("");n(e)}}();Tynt.st=function(){var a;return function(b,c,e,f){a=e||a;b=[N,"?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",u,"&g=",a,"&r=",encodeURIComponent(w(h.referrer)),"&href=",encodeURIComponent(w(i.location.href)),"&ts=",(new Date).getTime()];c="";if(f){c=[];e="";for(var g in f)if(f.hasOwnProperty(g)){c.push(e,encodeURIComponent(g),"=",encodeURIComponent(f[g]));e="&"}c="&"+c.join("")}n(b.join("")+c)}}();var ha=
{production:"32867010",staging:"17118521",demo:"17118521",dev:"17118521",test:"17118521"},X=function(){var a,b,c;b=Math.floor(Math.random()*1E8+1)+1E8;a=typeof Tynt.e==="undefined"||z(Tynt.e.toString())===""?"production":Tynt.e.toString().replace("-","");a=ha[a];c=encodeURIComponent;var e;a:{e=F(Tynt);for(var f=0;f<e.length;f++)if(e[f].length===22&&e[f].toString().indexOf("!")<0){e=e[f];break a}e=void 0}c=c("g="+e.toString.call(e));b=["http://pubads.g.doubleclick.net/gampad/ad?iu=/",a,"/ISP_START&sz=1x1&t=",
c,"&c=",b].join("");(new Image(1,1)).src=b},I=false;q=function(a){var b;if(b=typeof a.sic==="object"&&a.sic!==null){a=a.sic;b=[];for(var c in a)a.hasOwnProperty(c)&&b.push(c);b=b.length===0}if(!b&&!I){X();I=true}};if(typeof tyntLoadMethod!=="undefined"){if(Tynt.e||Math.random()<0.001)Tynt.st("lm",tyntLoadMethod,u,{lmEx:tyntLoadException});if(typeof TYNT_IN_DFP!=="undefined")if(tyntLoadMethod===TYNT_IN_DFP){X();I=true}else tcLifeCycleCallbackFunctions.afterIpBlockCheck.push(q)}else typeof tcLifeCycleCallbackFunctions!==
"undefined"&&tcLifeCycleCallbackFunctions.afterIpBlockCheck.push(q);if(Tynt.c)q=function(){};else{Tynt.c=true;Tynt.m=Tynt.m||[];Tynt.n=Tynt.n||[];q=function(){var a=true,b,c=function(e,f){var g;g=(g=z(f))?g.split(/\s+/i).length:0;var d={id:u,wc:g,c:f,f:a?1:0,t:U};E(e,d);a=false;g=d.trace_type;delete d.trace_type;var j=d.g;delete d.g;for(var k=[],l=["id","wc","f","w","h","t","c"],o=0;o<l.length;o++){var y=l[o],s=d[y];s&&k.push([y,encodeURIComponent(s).replace(/\'/g,"%27")]);delete d[y]}for(var m in d)if(d.hasOwnProperty(m))(l=
d[m])&&k.push([m,encodeURIComponent(l).replace(/\'/g,"%27")]);m=[];o=2048-(("http://"+v+"/a/t/x#?").length+(3+j.length)+5);y=k.length;var x=s=0,t=0,J,B,K,C,D=0;for(m[D]={g:j,tp:null};s<y&&m.length<35;){J=k[s][0];d=k[s][1];K=J.length+2;B=o-K-x;if(B>0){l=d.substring(t,t+B);C=l.slice(-2).indexOf("%");if(C>-1){l=d.substring(t,t+B-2+C);x+=C+2}x+=l.length+K;t+=l.length;m[D][J]=l}else x=o;if(x>=o){m[++D]={g:j,p:D};x=0}if(t>=d.length){s++;t=0}}m[0].tp=m.length;n(v+"/b/t/"+g+"?"+Q(m[0]));for(j=1;j<m.length;j++)n(v+
"/b/x/"+g+"?"+Q(m[j]))};if(i.addEventListener){navigator.userAgent.match(/Firefox\/2\b/)||r.addEventListener("copy",V,false);i.addEventListener("mousedown",W,false);i.addEventListener("dragleave",H,false);i.addEventListener("dragexit",H,false);h.addEventListener("contextmenu",ga,false)}else{r.attachEvent("oncopy",V);h.getElementsByTagName("html")[0].attachEvent("ondragleave",H);r.attachEvent("onmousedown",W)}if(h.cookie.indexOf("tracertraffic=")!==-1)if(!h.referrer||h.referrer.indexOf(i.location.host)==
-1)$("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");ca();da();return function(e,f){if(!h.getElementById("tyntSh")){var g,d,j;if(f)if(!h.selection||!h.selection.createRange){d=getSelection();j=d.rangeCount>0&&d.getRangeAt(0);g=d.toString()}else{d=h.selection.createRange();j=d.duplicate();g=d.text}var k=e.src;if(k&&!g&&fa(k)){d={trace_type:3,g:S(k),w:e.width,h:e.height};for(j=0;j<Tynt.n.length;j++)Tynt.n[j](d,k);c(d,k)}else if(g&&z(g).length&&e.nodeName!="TEXTAREA"&&e.nodeName!="INPUT"){k=
ea(g);d={trace_type:1};if(k)b=S(g);d.g=b;for(var l=true,o=0;o<Tynt.m.length;o++)l=l&&Tynt.m[o](d,g,j,k);k&&l&&c(d,g)}}}}}if(!(/tracer=test|tracer=no_tracing|disableTracer=/.test(i.location.href)||/disableTracer=y/.test(h.cookie)))var G=q()};Tynt.TCL=function(i,h){h.body?ia(i,h):setTimeout(function(){Tynt.TCL(window,document)},300)}})();Tynt.TCL(window,document)};
