(function(c){c=window[c];var
adz=c.gat('adz'),ins='ins',ext={ipe:function(p){return/[^\s]+(?=\.(jpg|jpeg|gif|png))/i.test(p);},dut:decodeURIComponent,iie:function(){return navigator.userAgent.search("MSIE")>-1},cfh:function(w,h,m,c){var _s=this;if(_s.iml||_s.ipe(m)){return _s.ctg('img',{src:m,style:'border:0',width:w,height:h});}
var m=m+'?'+_s.bkv({getlink:c},true),pm=_s.ctg('param',{name:'movie',value:m}),ps=_s.ctg('param',{name:'allowScriptAccess',value:'always'}),on=_s.iie()?'':_s.ctg('object',{type:'application/x-shockwave-flash',data:m,width:w,height:h},pm+ps);return _s.ctg('object',{classid:'clsid:d27cdb6e-ae6d-11cf-96b8-444553540000',width:w,height:h,align:'middle'},pm+ps+on);},pgc:function(l,i){var _s=this,_b=_s.gat('bid');l=l.replace('&ap_agent_uid=','&ap_agent_uid='+_b)
return _m.jay('http:/',_s.gat('app'),'Ads',_s.gat('pid'),_b,'pgc.ba','/')+'?'+_s.bkv({i:i,r:l},true);},scp:function(t,l){if(!t)return'';if(t.length<l)return t;var r='',c=new RegExp('[a-zA-Z0-9\.=+_-\|\\/\?\>\<\' ]');this.ech(t,function(){if(l<1)
return false;r+=this;l-=c.test(this)?0.8:1;});return r+'...';},bpg:function(o){var
_s=this,_a={t:_s.dut(o.t),c:o.c,p:o.p,l:_s.pgc(o.l,o.i)},_n=_s.cnd('ins',{onclick:function(){window.open(_a.l);},className:'a'}),_p=_s.cnd('img',{src:_a.p}),_t=_s.cnd(ins,{className:'t'},_s.scp(_a.t,18)),_c=_s.cnd(ins,{className:'b'},'$&nbsp;'+_a.c);_s.apc(_n,[_p,_t,_c]);_s.apc(_s.gat('adl'),_n);},bba:function(o){var
_s=this,_a=o;var
_n=_s.cnd(ins,{onclick:function(){window.open(_a.l);},className:'a'}),_p=_s.cnd(ins,{className:'p'},_s.cfh(_a.pw,_a.ph,_a.p,_a.l)),_t=_s.cnd(ins,{className:'t'},_s.dut(_a.t));_s.apc(_n,[_p,_t]);_s.apc(_s.gat('adr'),_n);},bbr:function(o){var
_s=this,_a={w:610,h:'auto',p:o.p,l:o.l},_n=_s.cnd(ins,{style:'width:'+_a.w+'px;border:0;',id:'blog468x60Banner'},_s.ctg('a',{href:_a.l,target:'_blank'},_s.cfh(_a.w,_a.h,_a.p,_a.l)));_s.apc(_s.gat('adb'),_n);},log:c.cnd(ins,{id:'a_'+adz.id,onclick:function(){window.open("http://www.bloggerads.net");}}),adt:c.cnd(ins,{id:'t_'+adz.id}),adl:c.cnd(ins,{id:'l_'+adz.id}),adr:c.cnd(ins,{id:'r_'+adz.id}),adb:c.cnd(ins,{id:'b_'+adz.id}),din:function(i){this.cnd('img',{src:this.gat('imp')+'?'+this.bkv({ba:i.ba.join(','),pg:i.pg.join(','),pb:i.pb.join(',')},true)});},cti:function(t){clearInterval(t);t=null;}};c.ext(ext);c.sab(adz);c.apc(ext.adt,[ext.adl,ext.adr]);c.apc(adz,[ext.log,ext.adt,ext.adb]);var
tmr=setInterval(function(){if(c.px&&c.ba){c.cti(tmr);c.ljs(c.gat('pg1')+'?'+c.bkv({ids:c.px.slice(0,c.gat('abl')).join(','),len:c.gat('abl'),core:c.gat('cor')},true));tmr=setInterval(function(){if(c.ba&&c.pg&&c.pb){c.cti(tmr);var i={ba:[],pg:[],pb:[]},ct=c.gat('mxa');c.ech(c.ba,function(){if(ct--==0)return false;c.bba(this);i.ba.push(this.i);});c.pg.sort(function(){return Math.random()-Math.random();});c.ech(c.pg,function(){if(ct--==0)return false;c.bpg(this);i.pg.push(this.i);});c.ech(c.pb,function(){c.bbr(this);i.pb.push(this.i);});c.sab(c.gat('adz'),{style:'display:block;'});c.din(i);}},300);}},300);})(window['ba_px_core']);